from CheckingAccount import CheckingAccount
from SavingsAccount import SavingsAccount

student_a = SavingsAccount("Student A", 100, 10, 101, "R1010", .04)
student_b = CheckingAccount("Student B", 90, 0, 102, "R102",3)
student_a.print_customer_information()
student_b.print_customer_information()
student_b.deposit(50)
student_a.withdraw(500)
student_a.withdraw(10)
student_b.withdraw(10)
student_a.apply_interest()
student_a.print_customer_information()
student_b.print_customer_information()
print("\ntesting limits: \n")
student_c = CheckingAccount("Student C", 100, 10, 103, "R103",1)
student_c.print_customer_information()
student_c.withdraw(50)
student_c.withdraw(10)
student_c.print_customer_information()

print("\ntesting interest: \n")
student_d = SavingsAccount("Student D", 100, 10, 104, "R104",.01)
student_d.print_customer_information()
student_d.withdraw(50)
student_d.apply_interest()
student_d.print_customer_information()
student_d.apply_interest()
student_d.print_customer_information()